from pydantic import BaseModel
from typing import List, Optional
from datetime import datetime


class TranscriptLine(BaseModel):
    """A single line of meeting transcript"""
    speaker: str
    text: str
    timestamp: datetime
    confidence: Optional[float] = None


class ActionItem(BaseModel):
    """An action item detected from the meeting"""
    text: str
    assignee: Optional[str] = None
    priority: Optional[str] = "medium"
    due_date: Optional[str] = None
    confidence: float = 0.0


class MeetingSession(BaseModel):
    """Active meeting session"""
    session_id: str
    started_at: datetime = datetime.now()
    transcript: List[TranscriptLine] = []
    action_items: List[ActionItem] = []
    
    class Config:
        arbitrary_types_allowed = True


class MeetingSummary(BaseModel):
    """Meeting summary generated by AI"""
    session_id: str
    title: str
    summary: str
    key_points: List[str]
    decisions: List[str]
    action_items: List[ActionItem]
    participants: List[str]
    duration_minutes: int


class JiraTaskRequest(BaseModel):
    """Request to create a Jira task"""
    summary: str
    description: str
    project_key: str
    issue_type: str = "Task"
    assignee: Optional[str] = None
    priority: Optional[str] = "Medium"
